Delete article
Northeastern-Science-Magazine/nusci-backend pull request #282
Opened 2024-11-13 23:39 UTC by AlenGano

## Pull Request

[comment]: <> (Leave blank if a section does not apply.)

### Brief Summary
[comment]: <> (Put a brief summary of your changes.)
- Added methods for issue 256 (in Controller and Acessor, as well as the pre-remove hook)
- Added tests 

### Questions / Considerations for the Future
[comment]: <> (Note any questions, or things to note that might involve this PR in the future.)
- 
- 

### API Changes
[comment]: <> (Note any new endpoints, deleted endpoints, or updated endpoints.)
- created the delete article endpoint
- 

### Database Changes
[comment]: <> (Note changes to any database schemas.)
- pre-remove hook
- 

### New Tests
[comment]: <> (Note any new or modified test cases.)
- Test for invalid slug
- Test for valid slug

[comment]: <> (Put the ticket # this PR closes.)
Closes #

2024-11-14 00:07 UTC, Arushi55 requested changes
Some things to think about, especially to test whether or not the article itself is every actually deleted.
The hook is really neat though!

2024-11-14 00:07 UTC, Arushi55 commented on app/models/dbModels/article.js
> +    console.error('Error in pre-deleteOne hook:', e);
throw an actual error?

2024-11-14 00:07 UTC, Arushi55 commented on app/models/dbModels/article.js
> +    // changed name to IssueMapSchema
comments about changes from previous iterations seem unnecessary

2024-11-14 00:07 UTC, Arushi55 commented on app/databaseAccessors/articleAccessor.js
> +      const resp = await Article.deleteOne({ _id: article._id });
If this calls the delete hook for an issue map, when is this article actually deleted from the articles list itself?

2024-11-15 00:06 UTC, ethanszeto requested changes
Please rebase to main, the git diff is +4200 and you have 105 files changed. After that we can review

2024-11-21 14:30 UTC, ethanszeto commented
https://github.com/Northeastern-Science-Magazine/nusci-backend/pull/283

2024-11-21 14:30 UTC, closed without merging