#201 delete photo tag
Northeastern-Science-Magazine/nusci-backend pull request #286
Opened 2024-11-29 06:26 UTC by dsyamy

## Pull Request

[comment]: <> (Leave blank if a section does not apply.)

### Brief Summary
[comment]: <> (Put a brief summary of your changes.)
- Deletes an existing photo tag given tag name
- If tag name does not exist, throws error
- included 2 tests and works in conjunction with create photoTag
- applied the changes in using email rather than username id

### Questions / Considerations for the Future
[comment]: <> (Note any questions, or things to note that might involve this PR in the future.)
- 
- 

### API Changes
[comment]: <> (Note any new endpoints, deleted endpoints, or updated endpoints.)
- 
- 

### Database Changes
[comment]: <> (Note changes to any database schemas.)
- 
- 

### New Tests
[comment]: <> (Note any new or modified test cases.)
- 
- 

[comment]: <> (Put the ticket # this PR closes.)
Closes #

2024-12-01 05:59 UTC, suttonspindler requested changes
You're in a good place with this, and the organization is clean!  Just add the Authorizations to the routes and tests, use your discretion as to what makes logical sense (ie. Admins/Photographers).

Also when drafting your prs please fill out the "Closes #" at the bottom of the template so that it can link back to the ticket.  This makes reviewing easier as we can ensure all the requirements have been met.

2024-12-01 05:59 UTC, suttonspindler commented on app/controllers/articleController.js
> +      const comment = new InternalCommentCreate({ user: userID, comment:  req.body.comment });
(nit) extra space should not be added

2024-12-01 05:59 UTC, suttonspindler commented on app/routes/photoTagRoutes.js
> +photoTag.route("/delete/:tagName").delete(PhotoTagController.delete); //delete a photo tag
The ticket mentions this, but only Admins/Photographers should be allowed to delete (and create) photo tags.  Use your discretion when deciding who should be authorized, and work it into your tests

2025-02-26 23:09 UTC, closed without merging

2025-02-26 23:10 UTC, dsyamy commented
old branch